export const inputPlaceholderTranslations = {
  en: 'Choose a date',
  fr: 'Choisissez une date',
  es: 'Elige una fecha',
  de: 'Wählen Sie ein Datum',
  it: 'Scegli una data',
  nl: 'Kies een datum',
  pt: 'Escolha uma data',
  ja: '日付を選択',
  'zh-CN': '选择日期',
  'zh-TW': '選擇日期',
  ru: 'Выберите дату',
  'bg-BG': 'Изберете дата',
  cs: 'Vyberte datum',
  da: 'Vælg en dato',
  el: 'Επιλέξτε μια ημερομηνία',
  fi: 'Valitse päivämäärä',
  'hr-HR': 'Odaberite datum',
  hu: 'Válasszon egy dátumot',
  id: 'Pilih tanggal',
  ko: '날짜를 선택하세요',
  'lt-LT': 'Pasirinkite datą',
  nb: 'Velg en dato',
  pl: 'Wybierz datę',
  'pt-BR': 'Escolha uma data',
  'pt-PT': 'Escolha uma data',
  'ro-RO': 'Alegeți o dată',
  'sk-SK': 'Vyberte dátum',
  'sl-SL': 'Izberite datum',
  sv: 'Välj ett datum',
  th: 'เลือกวันที่',
  tr: 'Bir tarih seçin',
  vi: 'Chọn ngày',
};

export const ariaLabels = {
  en: { prevMonth: 'Go to previous month', nextMonth: 'Go to next month' },
  fr: { prevMonth: 'Aller au mois précédent', nextMonth: 'Aller au mois suivant' },
  es: { prevMonth: 'Ir al mes anterior', nextMonth: 'Ir al siguiente mes' },
  de: { prevMonth: 'Gehe zum vorherigen Monat', nextMonth: 'Gehe zum nächsten Monat' },
  it: { prevMonth: 'Vai al mese precedente', nextMonth: 'Vai al mese successivo' },
  nl: { prevMonth: 'Ga naar de vorige maand', nextMonth: 'Ga naar de volgende maand' },
  pt: { prevMonth: 'Ir para o mês anterior', nextMonth: 'Ir para o próximo mês' },
  ja: { prevMonth: '前の月へ', nextMonth: '次の月へ' },
  'zh-CN': { prevMonth: '转到上一个月', nextMonth: '转到下一个月' },
  'zh-TW': { prevMonth: '轉到上一個月', nextMonth: '轉到下一個月' },
  ru: { prevMonth: 'Перейти к предыдущему месяцу', nextMonth: 'Перейти к следующему месяцу' },
  'bg-BG': { prevMonth: 'Отиди на предишния месец', nextMonth: 'Отиди на следващия месец' },
  cs: { prevMonth: 'Přejít na předchozí měsíc', nextMonth: 'Přejít na další měsíc' },
  da: { prevMonth: 'Gå til forrige måned', nextMonth: 'Gå til næste måned' },
  el: { prevMonth: 'Μετάβαση στον προηγούμενο μήνα', nextMonth: 'Μετάβαση στον επόμενο μήνα' },
  fi: { prevMonth: 'Siirry edelliseen kuukauteen', nextMonth: 'Siirry seuraavaan kuukauteen' },
  'hr-HR': { prevMonth: 'Idi na prethodni mjesec', nextMonth: 'Idi na sljedeći mjesec' },
  hu: { prevMonth: 'Ugrás az előző hónaphoz', nextMonth: 'Ugrás a következő hónaphoz' },
  id: { prevMonth: 'Pergi ke bulan sebelumnya', nextMonth: 'Pergi ke bulan berikutnya' },
  ko: { prevMonth: '이전 달로 가기', nextMonth: '다음 달로 가기' },
  'lt-LT': { prevMonth: 'Eiti į ankstesnį mėnesį', nextMonth: 'Eiti į kitą mėnesį' },
  nb: { prevMonth: 'Gå til forrige måned', nextMonth: 'Gå til neste måned' },
  pl: { prevMonth: 'Przejdź do poprzedniego miesiąca', nextMonth: 'Przejdź do następnego miesiąca' },
  'pt-BR': { prevMonth: 'Ir para o mês anterior', nextMonth: 'Ir para o próximo mês' },
  'pt-PT': { prevMonth: 'Ir para o mês anterior', nextMonth: 'Ir para o próximo mês' },
  'ro-RO': { prevMonth: 'Mergi la luna anterioară', nextMonth: 'Mergi la luna următoare' },
  'sk-SK': { prevMonth: 'Prejsť na predchádzajúci mesiac', nextMonth: 'Prejsť na nasledujúci mesiac' },
  'sl-SL': { prevMonth: 'Pojdi na prejšnji mesec', nextMonth: 'Pojdi na naslednji mesec' },
  sv: { prevMonth: 'Gå till föregående månad', nextMonth: 'Gå till nästa månad' },
  th: { prevMonth: 'ไปยังเดือนก่อนหน้า', nextMonth: 'ไปยังเดือนถัดไป' },
  tr: { prevMonth: 'Önceki aya git', nextMonth: 'Sonraki aya git' },
  vi: { prevMonth: 'Đi đến tháng trước', nextMonth: 'Đi đến tháng sau' },
};

export const monthNameTranslations = {
  en: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  fr: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
  es: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
  de: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
  it: ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'],
  nl: ['Januari', 'Februari', 'Maart', 'April', 'Mei', 'Juni', 'Juli', 'Augustus', 'September', 'Oktober', 'November', 'December'],
  pt: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
  ja: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
  'zh-CN': ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
  'zh-TW': ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
  ru: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентяюрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
  'bg-BG': ['Януари', 'Февруари', 'Март', 'Април', 'Май', 'Юни', 'Юли', 'Август', 'Септември', 'Октомври', 'Ноември', 'Декември'],
  cs: ['Leden', 'Únor', 'Březen', 'Duben', 'Květen', 'Červen', 'Červenec', 'Srpen', 'Září', 'Říjen', 'Listopad', 'Prosinec'],
  da: ['Januar', 'Februar', 'Marts', 'April', 'Maj', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'December'],
  el: [
    'Ιανουάριος',
    'Φεβρουάριος',
    'Μάρτιος',
    'Απρίλιος',
    'Μάιος',
    'Ιούνιος',
    'Ιούλιος',
    'Αύγουστος',
    'Σεπτέμβριος',
    'Οκτώβριος',
    'Νοέμβριος',
    'Δεκέμβριος',
  ],
  fi: [
    'Tammikuu',
    'Helmikuu',
    'Maaliskuu',
    'Huhtikuu',
    'Toukokuu',
    'Kesäkuu',
    'Heinäkuu',
    'Elokuu',
    'Syyskuu',
    'Lokakuu',
    'Marraskuu',
    'Joulukuu',
  ],
  'hr-HR': [
    'Siječanj',
    'Veljača',
    'Ožujak',
    'Travanj',
    'Svibanj',
    'Lipanj',
    'Srpanj',
    'Kolovoz',
    'Rujan',
    'Listopad',
    'Studeni',
    'Prosinac',
  ],
  hu: [
    'Január',
    'Február',
    'Március',
    'Április',
    'Május',
    'Június',
    'Július',
    'Augusztus',
    'Szeptember',
    'Október',
    'November',
    'December',
  ],
  id: ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'],
  ko: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
  'lt-LT': [
    'Sausis',
    'Vasaris',
    'Kovas',
    'Balandis',
    'Gegužė',
    'Birželis',
    'Liepa',
    'Rugpjūtis',
    'Rugsėjis',
    'Spalis',
    'Lapkritis',
    'Gruodis',
  ],
  nb: ['Januar', 'Februar', 'Mars', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Desember'],
  pl: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'],
  'pt-BR': ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
  'pt-PT': ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
  'ro-RO': [
    'Ianuarie',
    'Februarie',
    'Martie',
    'Aprilie',
    'Mai',
    'Iunie',
    'Iulie',
    'August',
    'Septembrie',
    'Octombrie',
    'Noiembrie',
    'Decembrie',
  ],
  'sk-SK': ['Január', 'Február', 'Marec', 'Apríl', 'Máj', 'Jún', 'Júl', 'August', 'September', 'Október', 'November', 'December'],
  'sl-SL': ['Januar', 'Februar', 'Marec', 'April', 'Maj', 'Junij', 'Julij', 'Avgust', 'September', 'Oktober', 'November', 'December'],
  sv: ['Januari', 'Februari', 'Mars', 'April', 'Maj', 'Juni', 'Juli', 'Augusti', 'September', 'Oktober', 'November', 'December'],
  th: [
    'มกราคม',
    'กุมภาพันธ์',
    'มีนาคม',
    'เมษายน',
    'พฤษภาคม',
    'มิถุนายน',
    'กรกฎาคม',
    'สิงหาคม',
    'กันยายน',
    'ตุลาคม',
    'พฤศจิกายน',
    'ธันวาคม',
  ],
  tr: ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'],
  vi: [
    'Tháng Một',
    'Tháng Hai',
    'Tháng Ba',
    'Tháng Tư',
    'Tháng Năm',
    'Tháng Sáu',
    'Tháng Bảy',
    'Tháng Tám',
    'Tháng Chín',
    'Tháng Mười',
    'Tháng Mười Một',
    'Tháng Mười Hai',
  ],
};

export const dayNameTranslations = {
  en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  fr: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
  es: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
  de: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
  it: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
  nl: ['Zo', 'Ma', 'Di', 'Wo', 'Do', 'Vr', 'Za'],
  pt: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  ja: ['日', '月', '火', '水', '木', '金', '土'],
  'zh-CN': ['日', '一', '二', '三', '四', '五', '六'],
  'zh-TW': ['日', '一', '二', '三', '四', '五', '六'],
  ru: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  'bg-BG': ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  cs: ['Ne', 'Po', 'Út', 'St', 'Čt', 'Pá', 'So'],
  da: ['Søn', 'Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør'],
  el: ['Κυρ', 'Δευ', 'Τρί', 'Τετ', 'Πέμ', 'Παρ', 'Σάβ'],
  fi: ['Su', 'Ma', 'Ti', 'Ke', 'To', 'Pe', 'La'],
  'hr-HR': ['Ned', 'Pon', 'Uto', 'Sri', 'Čet', 'Pet', 'Sub'],
  hu: ['V', 'H', 'K', 'Sze', 'Cs', 'P', 'Szo'],
  id: ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'],
  ko: ['일', '월', '화', '수', '목', '금', '토'],
  'lt-LT': ['Sek', 'Pir', 'Ant', 'Tre', 'Ket', 'Pen', 'Šeš'],
  nb: ['Søn', 'Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør'],
  pl: ['N', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'Sob'],
  'pt-BR': ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  'pt-PT': ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  'ro-RO': ['Dum', 'Lun', 'Mar', 'Mie', 'Joi', 'Vin', 'Sâm'],
  'sk-SK': ['Ne', 'Po', 'Ut', 'St', 'Št', 'Pi', 'So'],
  'sl-SL': ['Ned', 'Pon', 'Tor', 'Sre', 'Čet', 'Pet', 'Sob'],
  sv: ['Sön', 'Mån', 'Tis', 'Ons', 'Tor', 'Fre', 'Lör'],
  th: ['อา.', 'จ.', 'อ.', 'พ.', 'พฤ.', 'ศ.', 'ส.'],
  tr: ['Paz', 'Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cts'],
  vi: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
};

export const japaneseDaysOfMonth = {
  1: '一',
  2: '二',
  3: '三',
  4: '四',
  5: '五',
  6: '六',
  7: '七',
  8: '八',
  9: '九',
  10: '十',
  11: '十一',
  12: '十二',
  13: '十三',
  14: '十四',
  15: '十五',
  16: '十六',
  17: '十七',
  18: '十八',
  19: '十九',
  20: '二十',
  21: '二十一',
  22: '二十二',
  23: '二十三',
  24: '二十四',
  25: '二十五',
  26: '二十六',
  27: '二十七',
  28: '二十八',
  29: '二十九',
  30: '三十',
  31: '三十一',
};

export const chineseDaysOfMonth = {
  'zh-CN': {
    1: '一',
    2: '二',
    3: '三',
    4: '四',
    5: '五',
    6: '六',
    7: '七',
    8: '八',
    9: '九',
    10: '十',
    11: '十一',
    12: '十二',
    13: '十三',
    14: '十四',
    15: '十五',
    16: '十六',
    17: '十七',
    18: '十八',
    19: '十九',
    20: '二十',
    21: '廿一',
    22: '廿二',
    23: '廿三',
    24: '廿四',
    25: '廿五',
    26: '廿六',
    27: '廿七',
    28: '廿八',
    29: '廿九',
    30: '三十',
    31: '三十一',
  },
  'zh-TW': {
    1: '一',
    2: '二',
    3: '三',
    4: '四',
    5: '五',
    6: '六',
    7: '七',
    8: '八',
    9: '九',
    10: '十',
    11: '十一',
    12: '十二',
    13: '十三',
    14: '十四',
    15: '十五',
    16: '十六',
    17: '十七',
    18: '十八',
    19: '十九',
    20: '二十',
    21: '廿一',
    22: '廿二',
    23: '廿三',
    24: '廿四',
    25: '廿五',
    26: '廿六',
    27: '廿七',
    28: '廿八',
    29: '廿九',
    30: '三十',
    31: '三十一',
  },
};

export const koreanDaysOfMonth = {
  1: '일',
  2: '이',
  3: '삼',
  4: '사',
  5: '오',
  6: '육',
  7: '칠',
  8: '팔',
  9: '구',
  10: '십',
  11: '십일',
  12: '십이',
  13: '십삼',
  14: '십사',
  15: '십오',
  16: '십육',
  17: '십칠',
  18: '십팔',
  19: '십구',
  20: '이십',
  21: '이십일',
  22: '이십이',
  23: '이십삼',
  24: '이십사',
  25: '이십오',
  26: '이십육',
  27: '이십칠',
  28: '이십팔',
  29: '이십구',
  30: '삼십',
  31: '삼십일',
};

export const thaiDaysOfMonth = {
  1: '๑',
  2: '๒',
  3: '๓',
  4: '๔',
  5: '๕',
  6: '๖',
  7: '๗',
  8: '๘',
  9: '๙',
  10: '๑๐',
  11: '๑๑',
  12: '๑๒',
  13: '๑๓',
  14: '๑๔',
  15: '๑๕',
  16: '๑๖',
  17: '๑๗',
  18: '๑๘',
  19: '๑๙',
  20: '๒๐',
  21: '๒๑',
  22: '๒๒',
  23: '๒๓',
  24: '๒๔',
  25: '๒๕',
  26: '๒๖',
  27: '๒๗',
  28: '๒๘',
  29: '๒๙',
  30: '๓๐',
  31: '๓๑',
};
